apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orchardcore-cms
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dotnet-ci-lab
  source:
    repoURL: https://github.com/OWNER/dotnet-ci-orchardcore.git
    targetRevision: main
    path: helm/orchardcore
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff: { duration: 20s, factor: 2, maxDuration: 3m }
